### ISSUE TITLE
Pressing the "Stop capturing button crashes the app

### ISSUE THREAD

**Issue by CasperStaahl** [P6-AAU-23/real-time-whiteboard-app#24]

**Comment by CasperStaahl** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: com.whiteboardapp, PID: 6138
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Canvas.drawColor(int, android.graphics.PorterDuff$Mode)' on a null object reference
        at com.whiteboardapp.controller.OverlayView.drawRectOnCanvas(OverlayView.java:182)
        at com.whiteboardapp.controller.OverlayView.drawRectFromPoints(OverlayView.java:143)
        at com.whiteboardapp.controller.CaptureActivity.analyseImage(CaptureActivity.java:255)
        at com.whiteboardapp.controller.CaptureActivity.lambda$createAnalysisUseCase$4$CaptureActivity(CaptureActivity.java:198)
        at com.whiteboardapp.controller.-$$Lambda$CaptureActivity$sdQ0Y81eF87_5AsiPdY328bUoVU.analyze(Unknown Source:2)
        at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$1$ImageAnalysis(ImageAnalysis.java:370)
        at androidx.camera.core.-$$Lambda$ImageAnalysis$qO2F3Tn7pfTvGyL-EvT8WWE0F0w.analyze(Unknown Source:4)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:121)
        at androidx.camera.core.-$$Lambda$ImageAnalysisAbstractAnalyzer$g-dcm6aZmGod2IWKPwN4CArIZzI.run(Unknown Source:8)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```
